# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular comment.', primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular insight.', primary_key=True, serialize=False)),
                ('tone', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular text.', primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this user.', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=20)),
                ('theme', models.CharField(choices=[('LI', 'Light'), ('DA', 'Dark')], default='LI', max_length=2)),
                ('mature_content', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textifai.User'),
        ),
        migrations.AddField(
            model_name='insight',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textifai.Text'),
        ),
        migrations.AddField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textifai.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textifai.Text'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textifai.User'),
        ),
    ]
