# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular insight.', primary_key=True, serialize=False)),
                ('tone', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular text.', primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='insight',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textifai.Text'),
        ),
    ]
