# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='time',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mature_content',
        ),
        migrations.AddField(
            model_name='text',
            name='mature_content',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(help_text='Enter text here'),
        ),
    ]
