# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textifai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, help_text='Enter a title for your entry', max_length=40),
        ),
    ]
