# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textifai', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
