# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('textifai', '0002_auto_20171026_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInsight',
            fields=[
                ('m_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular insight.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=24)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='m_id',
        ),
        migrations.RenameField(
            model_name='insight',
            old_name='id',
            new_name='m_id',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='id',
            new_name='m_id',
        ),
        migrations.AlterField(
            model_name='insight',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textifai.Text'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textifai.User'),
        ),
    ]
